site_name: QScaler
site_description: 'QScaler - Kubernetes-native queue worker autoscaler'
site_author: 'Quickube'
docs_dir: docs/
repo_url: https://github.com/quickube/QScaler
repo_name: quickube/QScaler
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
plugins:
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introduction: introduction.md
  - Getting Started:
    - Installation: getting_started/index.md
    - Setup Broker: getting_started/setup.md
  - Concepts:
      - Qworker: concepts/qworker.md
      - ScalerConfig: concepts/scalerconfig.md
  - User Guide:
      - Python SDK: usage/python_example.md
  - Developers: CONTRIBUTING.md