# permissions for end users to view qscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: qscale
    app.kubernetes.io/managed-by: kustomize
  name: qscaler-viewer-role
rules:
- apiGroups:
  - quickcube.com
  resources:
  - qscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quickcube.com
  resources:
  - qscalers/status
  verbs:
  - get
