# permissions for end users to edit qscales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: qscale
    app.kubernetes.io/managed-by: kustomize
  name: qscale-editor-role
rules:
- apiGroups:
  - github.com
  resources:
  - qscales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.com
  resources:
  - qscales/status
  verbs:
  - get
