---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quickube.com
  resources:
  - qworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quickube.com
  resources:
  - qworkers/finalizers
  - scalerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - quickube.com
  resources:
  - qworkers/status
  - scalerconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - quickube.com
  resources:
  - scalerconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
