---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - quickcube.com
  resources:
  - qworker
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quickcube.com
  resources:
  - qworker/finalizers
  - scalerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - quickcube.com
  resources:
  - qworker/status
  - scalerconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - quickcube.com
  resources:
  - scalerconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
