# permissions for end users to edit scalerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: qscale
    app.kubernetes.io/managed-by: kustomize
  name: scalerconfig-editor-role
rules:
- apiGroups:
  - quickcube.com
  resources:
  - scalerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quickcube.com
  resources:
  - scalerconfigs/status
  verbs:
  - get
