// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/quickube/QScaler/api/v1alpha1"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// RightSizeContainers provides a mock function with given fields: ctx, worker
func (_m *Server) RightSizeContainers(ctx context.Context, worker *v1alpha1.QWorker) error {
	ret := _m.Called(ctx, worker)

	if len(ret) == 0 {
		panic("no return value specified for RightSizeContainers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.QWorker) error); ok {
		r0 = rf(ctx, worker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with given fields: ctx
func (_m *Server) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sync provides a mock function with given fields: ctx
func (_m *Server) Sync(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
