apiVersion: quickube.com/v1alpha1
kind: ScalerConfig
metadata:
  name: redis-config
spec:
  type: redis
  config:
    host: redis-master.default.svc.cluster.local
    port: "6379"
    password:
#      value: Aa123456
      valueFrom:
        secretKeyRef:
          name: redis-password
          key: data