name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: go
          package-name: qscaler
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run build
        if: ${{ steps.release.outputs.release_created }}
        env:
          VERSION: ${{ steps.release.outputs.tag_name }}
          SHA: ${{ steps.release.outputs.sha }}
        run: make build

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          for file in artifacts/*
          do
            if [ -f "$file" ]; then
              echo $file 
              gh release upload ${{ steps.release.outputs.tag_name }} $file
            fi
          done
